### ISSUE TITLE
Rootless pixel

### ISSUE THREAD

**Issue by rakkarage** [PDDStudio/OTGSubs#8]
Says not supported with new rootless substratum and Andromeda on pixel xl

**Comment by PDDStudio** [comment]
@rakkarage Can you post a screenshot of what exactly you mean? (And also which Theme you're using). On my Pixel XL everything works fine (DU, rootless Substratum)

**Comment by rakkarage** [comment]
thanks.
sorry i guess i was mistaken about not supported but
i guess it is just that i don't know what i am doing
i just wanna make a simple theme to replace all fonts with ubuntu fonts
tried adding ttfs, found it needed zip... added ubuntu font zip from sybstratum template idk
built it and there are no check boxes or font header in substratum but crashes when click paint brush... is that how it would get applied if possible to create am font only theme for everything?
thanks
