### ISSUE TITLE
Easy to use?

### ISSUE THREAD

**Issue by svein83** [PDDStudio/OTGSubs#9]
How is this easy to use?

There's no info snywhere on which file formats to use for fonts, overlays, boot animations, or audio.

No info on how to make or get overlays, and which formats they dhould be saved in, no info on ANYTHING...

So the app may be easy to use, but can't be used, since there's nothing available to include...

**Comment by Kuntitled** [comment]
Right?

**Comment by 4PERTURE** [comment]
Sounds more like the app isn't for you two
